src/types/LoginProviders.ts
yarn.lock

Fix the value for the Keycloak Business BCeID identity provider hint.
Fixes [FSADT2-329](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-329)
This change was tested on local and dev environments.
No more details.

fix(login): update provider hint when logging with business bceid

---

.github/workflows/merge-main.yml
src/__test__/components/__snapshots__/BCHeader.test.tsx.snap
src/components/LeftPanel/index.tsx
yarn.lock

Feature: Show current release running in the left side pannel.
Bugfix: enable empty changelog for the cases we need to start a new deployment without changes in the code.
This change was tested locally.

Feat: show current version

---

src/views/NewLanding/index.tsx
src/views/NewLanding/styles.scss

Configured the breakpoints of the landing page, to make it fully responsive.
Jira Ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-273
Tested the page on different screen sizes.

Added breakpoints for the landing page

---

.github/openshift/deploy.frontend.yml
.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
CONTRIBUTING.md
README.md
src/__test__/components/__snapshots__/BCHeader.test.tsx.snap
src/components/LeftPanel/index.tsx

Update environment variable with proper name for SPAR repository, since the previous name came from the sample app repository.
Fixes [FSADT2-340](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-340)
Tested locally and with Docker.

feat: update variable name to match spar repo version

---

src/components/LeftPanel/index.tsx

Adds the react navigation in the left panel.
Jira ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-346
Can be tested by being in another route (like '/table') and then clicking on the "dashboard" item in the left panel, the application should go to the dashboard page.

fix: navigation added to left panel

---

src/components/Card/index.tsx
src/components/FavoriteActivities/index.tsx

Allow users to remove items from my favorites activities list
Jira ticket: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-322

feat: delete favorite activities function created

---

src/components/BCHeader/index.tsx

Small adjustment fixing environment variable name, to display the correct version.
No ticket related.
Validation can only be made after it is deployed.

fix: fixed env var name

---

src/components/BCGovLogo/styles.css
src/components/BCHeader/styles.scss
src/components/Card/styles.scss
src/components/EmptySection/styles.scss
src/components/PanelSectionName/styles.scss
src/theme/components-overrides.scss
src/views/NewLanding/styles.scss

Changed css unis from px to rem, where necessary.
[JIRA Ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-350)
Tested manually.

fix: changed css units to rem, where necessary

---

src/__test__/components/RecentActivities.test.tsx
src/components/ActivityTable/index.tsx
src/components/Card/FavoriteCard/index.tsx
src/components/Card/FavoriteCard/styles.scss
src/components/FavoriteActivities/index.tsx
src/components/FavoriteActivities/styles.scss
src/components/PageTitle/index.tsx
src/components/PageTitle/styles.scss
src/components/RecentActivities/index.tsx
src/components/RecentActivities/styles.scss
src/components/Subtitle/index.tsx
src/components/Subtitle/styles.css
src/components/Subtitle/styles.scss
src/layout/PublicLayout/styles.scss
src/theme/components-overrides.scss
src/views/Dashboard/dashboard.tsx

Fixing a11y issues on the dashboard page.
Regarding the overflow menu on the favorite cards issue (after closing it, the focus doesn't comeback to the correct element), it will not be addressed under this PR. More details on the [JIRA ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-335)
Run unit tests and manually tested with screen reader NVDA.

fix: fixed accessibility issues on the dashboard page

---

frontend/src/components/ApplicantInformation/index.tsx
frontend/src/views/Seedlot/SeedlotCreatedFeedback/index.tsx

Linked feedback page to form. No task related to this action.
Manually tested.
---
[Frontend](https://nr-spar-webapp-59-frontend.apps.silver.devops.gov.bc.ca/) available

feat: linked a class form to feedback page

---

frontend/src/components/Card/FavouriteCard/index.tsx
frontend/src/components/FavouriteActivities/index.tsx
frontend/src/components/PageTitle/index.tsx
frontend/src/enums/ActivityType.ts

Fixing small issues found during tests:
- Delay while loading cards in dashboard;
- Highlight/dehighlight bug;
- Card redirect;
- Dashboard cards refresh.
Fixes [FSADT2-536](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-536)
Tested manually
---
[Frontend](https://nr-spar-webapp-60-frontend.apps.silver.devops.gov.bc.ca/) available

fix: minor fixes on the favourite activities integration

---

docker-compose.yml
frontend/Dockerfile

Add docker-compose file and update react-serve version.
Fixes #53 
This was tested locally with docker.
---
[Frontend](https://nr-spar-webapp-64-frontend.apps.silver.devops.gov.bc.ca/) available

ci: add docker compose file and update react-serve version

---

frontend/src/components/SeedlotSummary/index.tsx
frontend/src/components/SeedlotSummary/styles.scss
frontend/src/views/Seedlot/SeedlotDetails/index.tsx
frontend/src/views/Seedlot/SeedlotDetails/styles.scss

Created the seedlot summary component for the seedlot details page. For now, the component is populated by static data. 
Also, the details page is only reachable directly thru the URL for now, so to see the changes, add `seedlot/details` to the URL. 
[Jita Ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-479)
Manually tested.
---
[Frontend](https://nr-spar-webapp-62-frontend.apps.silver.devops.gov.bc.ca/) available

feat: seedlot summary created

---

frontend/src/components/ApplicantSeedlotInformation/index.tsx
frontend/src/components/ApplicantSeedlotInformation/styles.scss
frontend/src/components/FormProgress/index.tsx
frontend/src/components/FormProgress/styles.scss
frontend/src/components/FormReview/index.tsx
frontend/src/components/FormReview/styles.scss
frontend/src/components/TitleAccordion/index.tsx
frontend/src/mock-api/endpoints/SeedlotRegistrationEndpoint.ts
frontend/src/mock-api/fixtures/SeedlotInfos.ts
frontend/src/mock-api/fixtures/index.ts
frontend/src/mock-api/models/index.ts
frontend/src/utils/ApiAddresses.ts
frontend/src/utils/ApiUtils.ts
frontend/src/views/Seedlot/SeedlotDetails/index.tsx

Implementation of components of the Seedlot details page.
Implements [FSADT2-480](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-480)
Manually tested.
---
[Frontend](https://nr-spar-webapp-66-frontend.apps.silver.devops.gov.bc.ca/) available

feat: create components for seedlot details page

---

frontend/src/components/NotificationsCentral/index.tsx

Change the prop value for a button in notification centre from 'field' to 'md'
Fixes #: [Jira ticket: FSADT2-595](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-595)
Manually tested locally, warning message is gone.

fix: changed the prop value for a button

---

frontend/src/App.tsx
frontend/src/components/FormProgress/index.tsx
frontend/src/components/FormProgress/styles.scss
frontend/src/components/SeedlotRegistrationProgress/index.tsx
frontend/src/views/Seedlot/CreateAClass/index.tsx
frontend/src/views/Seedlot/SeedlotDetails/index.tsx
frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
frontend/src/views/Seedlot/SeedlotRegistrationForm/styles.scss

Added the structure for the seedlot registration page and other minor fixes.
To access the page, click the "Complete registration" button on a seedlot details page.
[Jira Ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-548)
Manually tested.
---
[Frontend](https://nr-spar-webapp-74-frontend.apps.silver.devops.gov.bc.ca/) available

feat: created seedlot registration page structure

---

frontend/src/components/ApplicantInformation/index.tsx
frontend/src/components/SeedlotRegistrationSteps/OrchardStep/data.ts
frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/OrchardStep/styles.scss
frontend/src/components/SeedlotRegistrationSteps/OrchardStep/utils.ts
frontend/src/custom.scss
frontend/src/mock-api/endpoints/OrchardsEndpoint.ts
frontend/src/mock-api/endpoints/SeedlotRegistrationEndpoints.ts
frontend/src/mock-api/endpoints/index.ts
frontend/src/mock-api/fixtures/GeneticClasses.ts
frontend/src/mock-api/fixtures/Orchards.ts
frontend/src/mock-api/fixtures/index.ts
frontend/src/mock-api/models/index.ts
frontend/src/types/OrchardType.ts
frontend/src/types/SeedlotTypes/SeedlotOrchard.ts
frontend/src/utils/ApiAddresses.ts
frontend/src/utils/ApiUtils.ts
frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
frontend/src/views/Seedlot/SeedlotRegistrationForm/styles.scss

Created the orchard step for the seedlot registration process.
To validate the Lodgepole Pine species, you'll need a seedlot with that species. You can do that by creating a new anoe and selecting the option below.
Also the current list of valid Orchard IDs fixed on the mock server is:
```
{
id: '102',
name: 'Skimikin '
},
{
id: '132',
name: 'Yellow point'
},
{
id: '214',
name: 'Vernon'
},
{
id: '346',
name: 'Bailey'
},
{
id: '802',
name: 'Mcbean'
}
```
[Jira Ticket](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-596)
Manually tested
---
[Frontend](https://nr-spar-webapp-78-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and handed off to following workflow …

feat: created orchard step for seedlot registration

---

.github/workflows/cypress-nightly.yml

Updated work-directory and path on nightly job
- [ x ] Bug fix (non-breaking change which fixes an issue)
N/A
---
[Frontend](https://nr-spar-webapp-98-frontend.apps.silver.devops.gov.bc.ca/) available

fix: updated work-directory and path on nightly job

---

.github/workflows/merge-main.yml

Re-enables auto generation of release notes and versions.
Fixes [FSADT2-641](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-641) and the previous PR: #101 
This will be tested with this PR.
---
[Frontend](https://nr-spar-webapp-101-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Frontend](https://nr-spar-webapp-108-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and handed off to following …

ci: fix release workflow

---

frontend/package.json

Update version with old version, so npm can update with current new version.
This was tested with previous PRs.
---
[Frontend](https://nr-spar-webapp-111-frontend.apps.silver.devops.gov.bc.ca/) available

feat: fix app version
